### ISSUE TITLE
Edited on and Created on date needs to be in relative format.

### ISSUE THREAD

**Issue by vishwajeetraj11** [siinghd/question-tracker#11]
Ref: 
<img width="1307" alt="image" src="https://github.com/siinghd/question-tracker/assets/47270995/50285755-9ef3-4a75-86bc-97b9a1d91855">

Update the dates in the post card as relative date.
as in 1 hr ago, 2 secs ago.

**Comment by siinghd** [comment]
Fix : 90d9b9084caffb3e007047a287ccd45cd887be98
