### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by ManishBisht777** [siinghd/question-tracker#15]
![image](https://github.com/siinghd/question-tracker/assets/89926834/f4a75149-c31f-4e30-aed6-550496bda2fe)

currently the site is not responsive make sure the site is responsive for all devices

Dividing the task into subtasks -

1) make the question page responsive
2) make the question details page responsive

**Comment by siinghd** [comment]
Fix in 340ee78c772e146690d88189c1c8142233f4d455 , still ui needs improvement but going towards that
