### ISSUE TITLE
Your questions and Ask a question panels should be differentiated

### ISSUE THREAD

**Issue by SwetanshuSingh** [siinghd/question-tracker#7]
**Reason / Context:**
 Why do we need this improvement?
 Users should be able to differentiate between the sections and which one is currently selected.

**Are you working on this issue?**
Yes

![issue_hsingh 2jpg](https://github.com/siinghd/question-tracker/assets/71164524/c31c6ab4-759f-41ff-aabc-6958cebb70da)

**Comment by siinghd** [comment]
Fix in Fix in 340ee78c772e146690d88189c1c8142233f4d455 
Move your questions in sort by and changed ask question ui
