### ISSUE TITLE
Fix the card layout while on response to response to response 

### ISSUE THREAD

**Issue by siinghd** [siinghd/question-tracker#9]
Currently when there is response to response and to response the card layout looks bad, it should columnar layout

![image](https://github.com/siinghd/question-tracker/assets/38940603/d6dde0fa-1b23-4587-9ea8-2ea2c834575b)

**Comment by SwetanshuSingh** [comment]
like this @siinghd 
![image](https://github.com/siinghd/question-tracker/assets/71164524/ff2d5823-2a44-47da-b1ad-fab893f817ac)
